# Site settings
title: BruAristimunha 
email: b.aristimunha@gmail.com  
description: Personal Site
baseurl:
url: 
twitter_username:
github_username:  bruAristimunha

# Build settings
markdown: kramdown
permalink: pretty
